apiVersion: v1
kind: Pod
metadata:
  name: busybox 
spec:
  tolerations:
  - key: role
    operator: Equal
    value: app
    effect: NoSchedule
  containers:
  - name: test-container
    image: busybox
    command: [ "sh", "-c", "while true; do sleep 3600; done;" ]
